### PR TITLE
Feature kafka

### PR DESCRIPTION
**Pull request by AgentChunk**
Branch now sends and receives messages through kafka to the branch.t topic. Will update other branch services based on the messages received.

### CODE REVIEW

**Comment by jurczakn** [comment]
You need to pull from dev again and fix merge conflicts

**Comment by AgentChunk** [comment]
Merged with dev

**Comment by AgentChunk** [comment]
Don't we need the configuration code so the receiver knows what topics to listen for?

**Comment by palagnajr** [comment]
@AgentChunk the only real configuration needed are the ones that I mentioned in the Revalution chat. Which is three lines in the properties file. The receiver knows which topics to listen for depending on the string that you put on the @KafkaListener annotation (yes, the topic could be in a static final variable in a Utility class, is not 100% necessary in the properties file).

**Comment by AgentChunk** [comment]
Separated the batch topic into batch.register, batch.update, and batch.delete topics

**Comment by SChrissndyer** [comment]
when sending a kafka message it fires a checker if the uuid has been checked it uses what it already has if not i checks the list of other uuids

**Pull request merged**
